### ISSUE TITLE
Creating a scalar variable

### ISSUE THREAD

**Issue by samharrison7** [schaefed/mo_netcdf#5]
Great work on the library, very useful!

Am I right in thinking there is no way to create a scalar variable at the moment? I.e. without any dimensions? Ideally I'd like to do something like:

```
var = nc%setVariable('scalar_varname', 'i16')
call var%setData(42)
```

If I'm correct, would you be happy for me to submit a pull request to add this functionality?

Cheers,
Sam

**Comment by schaefed** [comment]
Hi @samharrison7 ,

nice to see some interest in this.

It seems, that you are right and it is currently not possible to create scalar variables. If you find the time to prepare a pull request, I'd be happy to get this in.

Just out of curiosity: are you already using this module or are you still in an exploration phase?

**Comment by samharrison7** [comment]
Thanks for the quick reply. I'll hopefully find some time over the next few weeks to get a PR together.

Yep I'm already using this for a model I'm writing (geospatial model of contaminant fate in soils and waters). It's a private repo at the moment, but will be released shortly and I'll send a link over when it is. This library has been super useful - so much easier than writing the native nf90 bindings.

**Comment by samharrison7** [comment]
That was a lot easier than expected 😁  See the pull request #6. 

FYI, I figured you could already create a scalar variable by passing an empty array to `setVariable`, but now you can do it without having to do that.
